package handler

import (
	"context"
	"log"

	"connectrpc.com/connect"

	echov1 "github.com/takekazu/golang-azd/pkg/gen/buf/echo/v1"        // generated by protoc-gen-go
	"github.com/takekazu/golang-azd/pkg/gen/buf/echo/v1/echov1connect" // generated by protoc-gen-connect-go
)

type EchoServer struct{}

func (s *EchoServer) Echo(
	ctx context.Context,
	req *connect.Request[echov1.EchoRequest],
) (*connect.Response[echov1.EchoResponse], error) {
	log.Println("Request headers: ", req.Header())
	res := connect.NewResponse(&echov1.EchoResponse{
		Message: req.Msg.Message,
	})
	res.Header().Set("X-Version", echov1connect.EchoServiceName)
	return res, nil
}
